### ISSUE TITLE
Implement push!

### ISSUE THREAD

**Issue by bryaan** [JuliaServices/ConcurrentUtilities.jl#26]
Can we add something like this?

```
function Base.push!(data::Lockable{Vector{T},ReentrantLock}, elements) where {T}
    lock(data) do vec
        push!(vec, elements)
    end
end
```

**Comment by quinnj** [comment]
I don't think it's really necessary. While not strict type piracy, this is generally considered "type light robbbery" in that we (the ConcurrentUtilities.jl) package don't own the `Vector` type, so we shouldn't be overloading for it.

But the bigger reason is that it's so little code, it just doesn't seem worth it to "hide" the fact that your `Lockable{Vector}` is actually a Lockable instead of a Vector.
